c: remove custom build features rules
Was causing me this:
```
$ make build
cd ffi && cargo build --release --no-default-features --features
"rust-secp256k1 std rlp"
   Compiling etcommon-block v0.3.4
error[E0465]: multiple rlib candidates for `secp256k1` found
 -->
/home/ia/.cargo/registry/src/github.com-1ecc6299db9ec823/etcommon-block-0.3.4/src/lib.rs:4:1
  |
4 | extern crate secp256k1;
  | ^^^^^^^^^^^^^^^^^^^^^^^
  |
note: candidate #1:
/home/ia/go/src/github.com/ETCDEVTeam/sputnikvm-ffi/c/ffi/target/release/deps/libsecp256k1-f0a96a45b5a06ebb.rlib
 -->
/home/ia/.cargo/registry/src/github.com-1ecc6299db9ec823/etcommon-block-0.3.4/src/lib.rs:4:1
  |
4 | extern crate secp256k1;
  | ^^^^^^^^^^^^^^^^^^^^^^^
note: candidate #2:
/home/ia/go/src/github.com/ETCDEVTeam/sputnikvm-ffi/c/ffi/target/release/deps/libsecp256k1-0c5866018d09e4bc.rlib
 -->
/home/ia/.cargo/registry/src/github.com-1ecc6299db9ec823/etcommon-block-0.3.4/src/lib.rs:4:1
  |
4 | extern crate secp256k1;
  | ^^^^^^^^^^^^^^^^^^^^^^^

error[E0463]: can't find crate for `secp256k1`
 -->
/home/ia/.cargo/registry/src/github.com-1ecc6299db9ec823/etcommon-block-0.3.4/src/lib.rs:4:1
  |
4 | extern crate secp256k1;
  | ^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to 2 previous errors

Some errors occurred: E0463, E0465.
For more information about an error, try `rustc --explain E0463`.
error: Could not compile `etcommon-block`.

To learn more, run the command again with --verbose.
Makefile:2: recipe for target 'build' failed
make: *** [build] Error 101
```